openapi: 3.0.0
info:
  title: Gateway Admin API
  version: 0.1.0
  description: Administrative endpoints for the gateway.
paths:
  /health:
    get:
      summary: Health Check
      responses:
        '200':
          description: Gateway is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
  /version:
    get:
      summary: Version Info
      responses:
        '200':
          description: Version information
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                    example: "0.1.0"
                  commit:
                    type: string
                    example: "abc1234"
